# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_packages:
  - covr
r_github_packages:
  - jimhester/lintr
after_success:
  - Rscript -e 'library(covr); codecov()'
notifications:
  slack: rcollaborators:vsKVUWorGw2xKn9H0yhPIC36
